debug: false
server:
  port: 9090
  servlet:
    session:
      timeout:
        3000
  tomcat:
    uri-encoding: utf-8
logging:
  path: ../logs/haikit-manage-project
spring:
  application:
    name: haikit-manage-project
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  mvc:
    contentnegotiation:
      favor-path-extension: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/heikit?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: heikit
    password: yRYWK6L52ed5yhhk
  
#thymeleaf:
#  prefix: classpath:/templates/  #prefix：指定模板所在的目录
#  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
#  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
#  suffix:  .btl
#  #encoding: UTF-8
#  #content-type: text/html
#  mode: HTML5

#mybatis
mybatis-plus:
  mapper-locations: classpath:/com/haikit/manage/dbcore/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.rejia.manage.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
         
beetlsql: 
  enabled: false
